// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkuRRKO1ruxufCtjIRK4XRvO47ZKwFfDA',
    appId: '1:779136535126:web:25333ddfabc93aea8289f7',
    messagingSenderId: '779136535126',
    projectId: 'mdgnews2-7dccc',
    authDomain: 'mdgnews2-7dccc.firebaseapp.com',
    storageBucket: 'mdgnews2-7dccc.appspot.com',
    measurementId: 'G-4T4ZHEC5BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAv2yY0D050dBJvLShGSrjINE7WdmUuaQ',
    appId: '1:779136535126:android:632ad64dff7cfd768289f7',
    messagingSenderId: '779136535126',
    projectId: 'mdgnews2-7dccc',
    storageBucket: 'mdgnews2-7dccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyFGvnx_qBpj8ZvPKIaUaW1CoDW8MEHIA',
    appId: '1:779136535126:ios:8a09f09e5108eb698289f7',
    messagingSenderId: '779136535126',
    projectId: 'mdgnews2-7dccc',
    storageBucket: 'mdgnews2-7dccc.appspot.com',
    iosClientId: '779136535126-qsuorc22pib8tjaa55fcl64m7atjts56.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdgnews2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyFGvnx_qBpj8ZvPKIaUaW1CoDW8MEHIA',
    appId: '1:779136535126:ios:d756a8888fc16c1c8289f7',
    messagingSenderId: '779136535126',
    projectId: 'mdgnews2-7dccc',
    storageBucket: 'mdgnews2-7dccc.appspot.com',
    iosClientId: '779136535126-r60o51qsvjb6mveahio3gfl5r9m4qq0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdgnews2.RunnerTests',
  );
}
